{% set name = "qiskit-aer" %}
{% set version = "0.15.1" %}
{% set build = 1 %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% set build = build + 200 %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0] | int %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e1c45f10467ec1c64b021d44b6ab9a69b645dfc444036960e057b3058f70c6dd

build:
  script:
    # cuQuantum only supports Volta+
    - export AER_CUDA_ARCH="7.0;7.5;8.0;8.6;9.0+PTX"  # [cuda_compiler != "None"]
    - CMAKE_GENERATOR="Ninja" {{ PYTHON }} -m pip install . -vv  # [not win]
  skip: true  # [(win64 and cuda_compiler != "None") or cuda_compiler_version not in ("None", "11.8", "12.5")]
  number: {{ build }}
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  script_env:
    - DISABLE_DEPENDENCY_INSTALL=ON
    - DISABLE_CONAN=ON
    - CMAKE_GENERATOR=Ninja
    - CMAKE_PREFIX_PATH=%PREFIX%  # [win]
    - CMAKE_BUILD_PARALLEL_LEVEL=1  # [cuda_compiler != "None"]
    - CUQUANTUM_ROOT=$PREFIX  # [cuda_compiler != "None"]
    - CUTENSOR_ROOT=$PREFIX  # [cuda_compiler != "None"]
    - AER_THRUST_BACKEND=CUDA  # [cuda_compiler != "None"]
    - AER_ENABLE_CUQUANTUM=ON  # [cuda_compiler != "None"]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}  # [(cuda_compiler_version or "").startswith("11")]
    # Only headers used from spdlog
    - spdlog

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.12.0                      # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [cuda_compiler != "None"]
    - cmake !=3.17,>=3.8
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - ninja
  host:
    - libblas
    - liblapack
    # Upstream builds with 3.1.2 but that has no osx arm64 build. Instead we
    # pin the latest known working version. See
    # https://github.com/Qiskit/qiskit-aer/issues/1742 where problems were
    # reported with 3.10.3
    - nlohmann_json <=3.10.2
    - pip
    - python
    - pybind11 >=2.12.0  # This constraint is for CUDA 12 and numpy 2.0, not for qiskit-aer
    - scikit-build >=0.11.0
    - setuptools >=40.1.0
    - spdlog
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler != "None"]
    # Qiskit Aer now uses both
    - custatevec                                # [cuda_compiler != "None"]
    - cutensornet                               # [cuda_compiler != "None"]
  run:
    - python
    - numpy >=1.16.3
    - psutil >=5
    - qiskit >=0.45.2
    - scipy >=1.0
    - cuda-version >={{ cuda_major }}.2,<{{ cuda_major+1 }}  # [(cuda_compiler_version or "").startswith("11")]
    - cuda-version >={{ cuda_major }}.0,<{{ cuda_major+1 }}  # [(cuda_compiler_version or "").startswith("12")]

test:
  source_files:
    - .stestr.conf
    - test/*
  commands:
    - pip check
    # perform the import test via CLI because we need to load the stub for CUDA 12
    - export CUDA_STUB="$PREFIX/lib/stubs/libcuda.so"  # [linux and (cuda_compiler_version or "").startswith("12")]
    - LD_PRELOAD="$CUDA_STUB" python -c "import qiskit_aer"  # [linux]
    - python -c "import qiskit_aer"                          # [not linux and build_platform == target_platform]
    # Ignore tests that require qiskit_qasm3_import which is not packaged in
    # conda-forge by using `-E test_save_statevector_for_qasm3_circuit`
    #
    # Ignore shot_branching tests that seem to be flaky in the upstream tests as well.
    - stestr run -E "test_save_statevector_for_qasm3_circuit|TestShotBranching|test_dynamic_circuit_with_shot_branching"  # [build_platform == target_platform and cuda_compiler_version == "None"]

    # The following used to work but broke with 0.15.0. See https://github.com/Qiskit/qiskit-aer/issues/2213
    # Ignore _GPU tests for CUDA builds because the environment does not have a GPU
    # - LD_PRELOAD="$CUDA_STUB" stestr run -E 'test_save_statevector_for_qasm3_circuit|_GPU'  # [linux and cuda_compiler_version != "None"]
  requires:
    - ddt
    - ipython
    - matplotlib-base
    - pip
    - seaborn
    - stestr
    - cuda-driver-dev  # [linux and (cuda_compiler_version or "").startswith("12")]

about:
  home: https://github.com/Qiskit/qiskit-aer
  summary: Qiskit Aer - High performance simulators for Qiskit
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leofang
    - wshanks
    - basnijholt
