{% set name = "qiskit-aer" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d87064b5e60a5bf2a88019d2b71e217f33d2009793fa7edea0bf08cf30e326e5
  patches:
    # qiskit-aer builds against a bundled blas on Windows. This patch adds a
    # USE_BUNDLED_BLAS_WIN cmake option to search for an installed blas library
    # instead
    - 0001-windows-find-blas.patch

build:
  script: CMAKE_GENERATOR="Ninja" {{ PYTHON }} -m pip install . -vv  # [not win]
  # Skip macOS build until https://github.com/Qiskit/qiskit-aer/issues/1689 is addressed
  skip: true  # [osx]
  number: 1
  script_env:
    - DISABLE_DEPENDENCY_INSTALL=ON
    - DISABLE_CONAN=ON
    - CMAKE_GENERATOR=Ninja
    - CMAKE_PREFIX_PATH=%PREFIX%  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake !=3.17,>=3.8
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ninja
  host:
    - libblas
    - liblapack
    - muparserx =4.0.8
    - nlohmann_json =3.1.2
    - numpy
    - pip
    - python
    - pybind11
    - scikit-build >=0.11.0
    - setuptools >=40.1.0
    - spdlog
  run:
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('muparserx', max_pin='x.x.x') }}
    - python
    - qiskit >=0.44.0
    - scipy >=1.0

test:
  source_files:
    - .stestr.conf
    - test/*
  imports:
    - qiskit_aer
  commands:
    - pip check
    - stestr run -E test_save_statevector_for_qasm3_circuit  # Ignore tests that require qiskit_qasm3_import which is not packaged in conda-forge
  requires:
    - ddt
    - ipython
    - matplotlib-base
    - numpy <1.25.0  # Temporary pin to avoid deprecation warnings, following https://github.com/Qiskit/qiskit-aer/pull/1871
    - pip
    - seaborn
    - stestr

about:
  home: https://github.com/Qiskit/qiskit-aer
  summary: Qiskit Aer - High performance simulators for Qiskit
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leofang
    - wshanks
