{% set name = "qiskit-aer" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1be397975ae9a9358217f9613501a5fcc1f187f5a820386d3c26b84f671ac7b3

build:
  script: CMAKE_GENERATOR="Ninja" {{ PYTHON }} -m pip install . -vv
  # Skip Windows build until qiskit-terra has a Windows build
  # Skip macOS build until https://github.com/Qiskit/qiskit-aer/issues/1689 is addressed
  skip: true  # [win or osx]
  number: 0
  script_env:
    - DISABLE_DEPENDENCY_INSTALL=ON
    - DISABLE_CONAN=ON

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake !=3.17,>=3.8
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - ninja
  host:
    - libblas
    - liblapack
    - muparserx =4.0.8
    - nlohmann_json =3.1.2
    - numpy
    - pip
    - python
    - pybind11
    - scikit-build >=0.11.0
    - setuptools >=40.1.0
    - spdlog
  run:
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('muparserx', max_pin='x.x.x') }}
    - python
    - qiskit-terra >=0.21.0
    - scipy >=1.0

test:
  source_files:
    - .stestr.conf
    - test/*
  imports:
    - qiskit_aer
  commands:
    - pip check
    - stestr run
  requires:
    - ddt
    - ipython
    - matplotlib-base
    - pip
    # Pin qiskit-terra for now because its deprecation warnings fail the tests for aer less than 0.12.1
    - qiskit-terra <0.24
    - seaborn
    - stestr

about:
  home: https://github.com/Qiskit/qiskit-aer
  summary: Qiskit Aer - High performance simulators for Qiskit
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leofang
    - wshanks
